Added storage

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -56,6 +56,13 @@ jobs:
       - name: Apply Ingress Config
         run: kubectl apply -f k8s/ingress.yaml
 
-      - name: Test Health Endpoint
+      - name: Test Flask health endpoint
+        shell: powershell
         run: |
-          curl --fail -H "Host: flask.local" http://127.0.0.1/health
+          $response = Invoke-WebRequest -Uri "http://127.0.0.1/health" -Headers @{Host="flask.local"}
+          if ($response.StatusCode -ne 200) {
+            Write-Error "Health check failed with status code $($response.StatusCode)"
+            exit 1
+          }
+          Write-Host "Health check passed with status code $($response.StatusCode)"
+
